# Generated by Django 5.2.6 on 2025-09-30 09:52

import eshop_products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=eshop_products.models.upload_gallery_image_path)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
