# Generated by Django 5.2.6 on 2025-10-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0003_product_category'),
        ('eshop_tag', '0003_remove_tag_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(blank=True, to='eshop_tag.tag'),
        ),
    ]
