# Generated by Django 5.2.6 on 2025-10-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0005_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'گالری تصویر', 'verbose_name_plural': 'گالری تصاویر'},
        ),
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نویسنده'),
        ),
    ]
