# Generated by Django 5.2.6 on 2025-10-10 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_product_category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'دسته بندی محصول', 'verbose_name_plural': 'دسته بندی محصولات'},
        ),
    ]
