# Generated by Django 5.2.6 on 2025-10-06 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_tag', '0002_alter_tag_options_alter_tag_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='products',
        ),
    ]
