# Generated by Django 5.2.6 on 2025-10-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_settings', '0002_sitesettings_about_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='copyright',
            field=models.CharField(blank=True, null=True, verbose_name='متن کپی رایت'),
        ),
    ]
