# Generated by Django 5.2.6 on 2025-10-16 09:00

import eshop_settings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_settings', '0003_sitesettings_copyright'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=eshop_settings.models.upload_gallery_image_path, verbose_name='تصویر'),
        ),
    ]
